#ifndef __link
#define __link


#include "BangunRuang/01-BangunRuang.hpp"
#include "BangunRuang/02-Balok.hpp"
#include "BangunRuang/03-Kubus.hpp"
#include "BangunRuang/04-Bola.hpp"
#include "BangunRuang/05-Tabung.hpp"
#include "BangunRuang/06-LimasSegitiga.hpp"
#include "BangunDatar/01-BangunDatar.hpp"
#include "BangunDatar/02-Persegi.hpp"
#include "BangunDatar/03-PersegiPanjang.hpp"
#include "BangunDatar/04-Segitiga.hpp"
#include "BangunDatar/05-Trapesium.hpp"
#include "BangunDatar/06-BelahKetupat.hpp"
#include "SortingArray/01-SortingArray.hpp"

#endif